logLevel=INFO
#Capabilities
coverageCollectionEnabled=true
classScanningEnabled=true
contextPropagationEnabled=true
testTracingEnabled=false
#Heartbeat status reporting
heartbeatEnabled=true
heartbeatInterval=30000
