/**
 * Copyright 2020 - 2022 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.epam.drill.agent.test2code.common.api

import kotlinx.serialization.*

/**
 * Ast metadata about the method of class or file
 * @param classname the full name of the class
 * @param name the name of the method
 * @param params the list of parameters of the method
 * @param returnType the method return type
 * @param probesCount the count of probes of the method
 * @param probesStartPos where to start probes
 * @param bodyChecksum the checksum of the method body
 */
@Serializable
data class AstMethod(
    val classname: String,
    val name: String,
    val params: String,
    val returnType: String,
    val probesCount: Int,
    val probesStartPos: Int,
    val bodyChecksum: String,
    val annotations: Map<String, List<String>>? = null,
    val classAnnotations: Map<String, List<String>>? = null,
)

@Serializable
data class MethodCoverage(
    val signature: String,
    val bodyChecksum: String,
    val testId: String?,
    val testSessionId: String?,
    @Serializable(with = BitSetSerializer::class)
    var probes: Probes,
){
    // Generated by IDEA, all fields included
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as MethodCoverage

        if (signature != other.signature) return false
        if (probes != other.probes) return false
        if (testId != other.testId) return false
        if (testSessionId != other.testSessionId) return false

        return true
    }

    // Calculating hashcode value without probes.
    // We need to update ExeclassData instead of storing a new one.
    override fun hashCode(): Int {
        var result = signature.hashCode()
        result = 31 * result + testId.hashCode() + testSessionId.hashCode()
        return result
    }
}
