name: Check
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, preset: linuxX64}
          - {os: windows-latest, preset: mingwX64}
#          - {os: macos-12, preset: macosX64} deprecated in GitHub Actions
          - {os: macos-14, preset: macosArm64}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: zulu
      - uses: gradle/wrapper-validation-action@v1
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64' || matrix.config.preset == 'macosArm64'
        run: chmod +x ${{ github.workspace }}/gradlew
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64' || matrix.config.preset == 'macosArm64'
        run: chmod +x ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64' || matrix.config.preset == 'macosArm64'
        run: ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'mingwX64'
        run: ${{ github.workspace }}/setup-shared-libs.bat
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.config.preset }}
          path: ${{ github.workspace }}/*/build/reports/*
