name: Build & publish drill artifacts
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish_for_nix:
    name: Publish for nix platforms (macOS, Linux)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: |
          gradle --no-daemon -si publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m

  build_and_publish_for_win:
    name: Publish for Windows platform (Windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: |
          gradle -si publishMingwX64ZipPublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
