name: Build & publish drill artifacts
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish-linuxx64:
    name: Publish for Linux X64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: gradle -si publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4096m
  publish-macosx64:
    name: Publish for MacOS x64
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: gradle -si publishMacosX64ZipPublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4096m
  publsih-windowsx64:
    name: Publish for Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: gradle -si publishMingwX64ZipPublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4096m
