name: Publish common artifacts
on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, preset: linuxX64, task: publish}
          - {os: macos-latest, preset: macosX64, task: publishMacosX64PublicationToMavenRepository}
          - {os: windows-latest, preset: mingwX64, task: publishMingwX64PublicationToMavenRepository}
    name: Publish for ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s ${{ matrix.config.task }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g
      - id: to_version
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: return context.payload.release.tag_name.replace(/^v/, '');
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/distributions/${{ matrix.config.preset }}-${{ steps.to_version.outputs.result }}.zip
          asset_name: test2code-plugin-${{ steps.to_version.outputs.result }}.zip
          asset_content_type: application/zip
