name: Tag develop
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - run: git fetch
      - name: Next Prerelease SemVer
        id: next_semver
        uses: Drill4J/semver-tag-action@v0.1.0
        with:
          type: prerelease
      - name: Create Prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.next_semver.outputs.tag }}
          release_name: ${{ steps.next_semver.outputs.tag }}
          prerelease: true
